### ISSUE TITLE
Pull Request Lab: Issues

### ISSUE THREAD

**Issue by LuckyFlower2995** [hunter-classes/spring-2021-135-lab-07-Adrian-Mok15#3]
There isn't much to comment here. The comments in funcs.cpp are helpful in reading the code and its interesting how you used a void function in main to test the code. You have some unneeded code in your code that you didn't delete and there are some parts that can be shortened (maybe) , but everything else is fine. I'm probably just going to clean up your lab.

**Comment by Adrian-Mok15** [comment]
Ok, thanks!
